- name: Inspect Network
  hosts: localhost
  connection: local
  gather_facts: true

  tasks:
    - name: Print OS family
      debug:
        msg: "{{ ansible_os_family }}"
        
    - name: Gather OS Information
      include_tasks: ../roles/common/linux/tasks/os_info.yml
      when: ansible_os_family == "Debian"

    - name: Include DNS tasks
      include_tasks: ../roles/inspect/network/linux/tasks/dns.yml
      when: ansible_os_family == "Debian"

    - name: Include Network Engine tasks
      include_tasks: ../roles/inspect/network/linux/tasks/network_engine.yml
      when: ansible_os_family == "Debian"
