- name: Inspect DNS config on Linux and Windows
  hosts: localhost
  connection: local
  gather_facts: true

  tasks:
    - name: Print OS family
      debug:
        msg: "{{ ansible_os_family }}"

    - name: Include Linux DNS tasks
      include_tasks: ../roles/inspect/network/linux/tasks/dns.yml
      include_tasks: ../roles/inspect/network/linux/tasks/network_engine.yml
      when: ansible_os_family == "Debian"